### ISSUE TITLE
CLI actions for launching tests on Flood

### ISSUE THREAD

**Issue by ivanvanderbyl** [flood-io/element#142]
It'd be neat to be able to launch a Flood from the Element CLI. Something like:

```shell
element flood run script.ts
```

We'd need some other details for handling login token and maybe listing running floods and results.

**Comment by ivanvanderbyl** [comment]
We'd need to have a setup option for configuring the project and stream to launch the test in, and optionally take an cli flag to change it, but it'd be terrible user experience to supply it each time.

I think this will be blocked on #133

**Comment by sonnguyenmau** [comment]
Hi Ivan, as discussed, this is the list of commands that we're going to do. Please help to review them, including the wording in messages if you have time. Thank you!
1. Authenticate user
**element flood authenticate <api_token>** 
=> make a request via API v2 to get customer's account info. 
=> If success, display this message: "Successfully authenticated." and save the token for later uses. 
=> Otherwise, raise error: "The token you have input is invalid. Please check and try again."

For the rest of commands (from #2), whenever user runs a command without being authenticated, raise this error: "You need to be authenticated first. Please use this command: element flood authenticate <your_api_token>"

2. List projects on Flood
**element flood project ls**
=> display list of projects
[in case there're no projects on Flood] => "There're no projects on Flood. Please go to the Flood UI to create one"

3. Select to use a project
**element flood use "project name"**
=> if success, display this message: "Using <project_name>"
=> otherwise, raise error: "No project found with name "<project_name>". Please check and try again"

For the rest of the commands (from #4), if users have not specified a project to use, whenever they run any of the commands below, raise this error:  "You're not currently using any project on Flood. Select to use a project first, using this command: element flood use 'project name'"

4. Print current project
**element flood project**
=> "Using <project_name> under <org_name> on Flood"

5. Run a flood on HOSTED grid
**element flood run 'path_to_testscript' --hosted --vu <number> --duration <minutes> --rampup <minutes>**
=> display list of running grids, together with this message: "? Select the grids you want to launch this flood on. Use Up/Down arrow keys to navigate, Space bar to select, Enter to finish"
[if no grids are selected but ENTER is pressed] => "At least 1 grid needs to be selected"
[if there're no running grids] => "There're no running grids. Please go to the Flood UI to launch a grid first"
=> after at least 1 grid has been selected, display this message: "You 're about to simulate 10,000 total users across 2 grids. Estimated usage will be 10,000 VUH. Are you sure? (Y/n)"
=> Y => 
"Click on the link below to view the flood details: 
https://app.flood.io/projects/29562/flood/1cOVPSAYcsJFfPZkXKCkm0p5LO8"

6. Run a flood on demand
**element flood run 'path_to_testscript' --vu <number> --duration <minutes> --rampup <minutes>**
=> display list of available regions, together with this message: "? Select the regions you want to launch this flood. Use Up/Down arrow keys to navigate, Space bar to select, Enter to finish"
[if no regions are selected but ENTER is pressed] => "At least 1 region needs to be selected"
=> after at least 1 region has been selected, display this message: "You 're about to simulate 10,000 total users across 2 regions. Estimated usage will be 10,000 VUH. Are you sure? (Y/n)"
=> Y => 
"Click on the link below to view the flood details: 
https://app.flood.io/projects/29562/flood/1cOVPSAYcsJFfPZkXKCkm0p5LO8"
