### ISSUE TITLE
Exit status of `element run test.ts` to reflect test passing/failing

### ISSUE THREAD

**Issue by mkj28** [flood-io/element#30]
**Is your feature request related to a problem? Please describe.**
Feature request. Use case: before the full load test runs in CI (like Jenkins) - validate that script is still functional - without spinning grid or using hours on flood.io

**Describe the solution you'd like**
return of `element run test.ts` to be not 0 if test failed. Right now regardless if test is passing or failing I am seeing "0" return code.

**Describe alternatives you've considered**
Some magic script to parse output?

**Additional context**
None

**Comment by ivanvanderbyl** [comment]
This sounds like a bug, it should definitely exit with none 0 status if the script fails for any reason and can't continue the loop.

**Comment by lachie** [comment]
We'd need to tighten the semantics around this &/or document. 

As of now, element cli is tuned for load testing-style semantics:
Test failures won't return non-zero because in a load testing context, its a valid outcome -- and valuable data... The script can continue on to the next loop whereupon it may or may not fail again.
The things that will return non-zero codes are things like a test script with a syntax error -- in the load testing context this is an error because the test can't be started.

I'm happy to talk over changing this, but I suspect that we won't end up doing so since it does make sense for load testing as it is now. Perhaps we can add a flag to change the behaviour.

**Comment by jkroepke** [comment]
Workaround using bash as wrapper:

```
#!/bin/bash

set -euo pipefail

npx element run "$@" 2>&1 | tee /dev/stderr | { { grep -q 'error ' && exit 1; } || true; }
```
just call `./element.sh run test.ts` and the exit code should reflect the result of the test or any compile or runtime errors in node.
