### ISSUE TITLE
Stepwise response time measurement

### ISSUE THREAD

**Issue by arjunUnniumbath** [flood-io/element#88]
hi All,

Wanted help regarding one of the configurations : 

1. What should be the configuration to show the response time "Step" wise in console?

1. Is there any way to exclude action delay in the final response time displayed?

**Comment by arjunUnniumbath** [comment]
@ivanvanderbyl  Would you be able to help with this request ?

**Comment by ivanvanderbyl** [comment]
@arjunUnniumbath in answer to your questions:

1. We don't support this as yet, but a PR would be welcome, I've created an issue for the feature, I think it would be a good idea #89 
2. Yes, but be careful comparing the results to anything else because you can't eliminate the time it takes Element to talk to the browser, the browser to act, and report back (up to a few ms). The `responseTimeMeasurement` setting accepts a few options:

* Possible values:
	 * - `"page"`: Record the document loading response time. This is usually what you consider response time on paged web apps.
	 * - `"network"`: Takes the mean response time of all network requests which occur during a step. This is useful for Single Page Application which don't actually trigger a navigation.
	 * - `"step"`: (Default) Records the wall clock time of a step. This is useful for Single Page Application which don't actually trigger a navigation.
	 * - `"stepWithThinkTime"`: Records the wall clock time of a step including `actionDelay` time.

**Comment by arjunUnniumbath** [comment]
Thank you !
