### ISSUE TITLE
Launch a load test loacally

### ISSUE THREAD

**Issue by dvmarco** [flood-io/element#92]
Hello,
First thanks for Open Sourcing this nice project.

**Feature description**

I would like to launch a load test locally, from what I have seen it looks I need to launch 1 cli per users. Have I missed something ?

**Describe the solution you'd like**

It would be great to have a "Running the test script:" option that let you set a number of virtual users that you would like to simulate.

element run test.ts --virtual-users=50

**Describe alternatives you've considered**

I know I can use the element run command multiple times but it doesn't look like a good  solution to me.

**Additional context**

![new feature request](https://user-images.githubusercontent.com/57662776/68676503-7b2d8e00-055a-11ea-9276-c233e58d3c30.png)

**Comment by ivanvanderbyl** [comment]
Hi @dvmarco, this isn't currently possible due to the need to run multiple browser instances locally, which by default utilize all available resources of your machine. 

We're just finishing supporting local runs with multiple users in separate containers using [Flood Agent](https://agent.flood.io/), but this is still in beta.
