### ISSUE TITLE
Can not run flood element locally with test data

### ISSUE THREAD

**Issue by tanpnguyen** [flood-io/element#93]
Hi,

I am trying to build my script with test data in csv file. I followed this guide [Here](https://element.flood.io/docs/1.0/examples/unique-test-data) but it threw an error 

`error: [Iteration: 1] Error in Runner Loop: Error: Test data exhausted, consider making it circular?
Error: Test data exhausted, consider making it circular?
    at Test.runWithCancellation (C:\Users\tanpnguyen\AppData\Roaming\npm-cache\_npx\22696\node_modules\@flood\element-cli\node_modules\@flood\element\src\runtime\Test.js:93:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
+2s error: flood element error: Test data exhausted, consider making it circular?
process exited
process exited - with error`

I have also tried to run with the "sample" project [Here](https://github.com/flood-io/load-testing-playground/blob/master/element/test-data/README.md) but still have the same error.

My flood element version is 1.0.8-stable.1

**Comment by ivanvanderbyl** [comment]
Hi @tanpnguyen, this is the expected behaviour: when your test data is exhausted, the process will exit.

You can fix this by making it circular, by simply appending `.circular()` to the end of your test data setup. This will cause it to return to the first item once it reaches the end of the list of test data entries.
